import { Keybinding } from "@/types/Keybindings";

export const DefaultKeybinds: Keybinding[] = [
  {
    id: "1",
    scope: "Blackjack PreRound",
    action: "Start Game",
    key: "enter",
  },
  {
    id: "2",
    scope: "Blackjack Round",
    action: "Remove Last Card",
    key: "backspace",
  },
  {
    id: "3",
    scope: "Blackjack Round",
    action: "Stand",
    key: "enter",
  },
  {
    id: "24",
    scope: "Blackjack Round",
    action: "Hit",
    key: "space",
  },
  {
    id: "4",
    scope: "Blackjack Round",
    action: "Payout & End",
    key: "enter",
  },
  {
    id: "22",
    scope: "Blackjack Round",
    action: "Double",
    key: "x",
  },
  {
    id: "23",
    scope: "Blackjack Round",
    action: "Split",
    key: "s",
  },
  {
    id: "5",
    scope: "Blackjack Round",
    action: "A",
    key: "1",
  },
  {
    id: "6",
    scope: "Blackjack Round",
    action: "2",
    key: "2",
  },
  {
    id: "7",
    scope: "Blackjack Round",
    action: "3",
    key: "3",
  },
  {
    id: "8",
    scope: "Blackjack Round",
    action: "4",
    key: "4",
  },
  {
    id: "9",
    scope: "Blackjack Round",
    action: "5",
    key: "5",
  },
  {
    id: "10",
    scope: "Blackjack Round",
    action: "6",
    key: "6",
  },
  {
    id: "11",
    scope: "Blackjack Round",
    action: "7",
    key: "7",
  },
  {
    id: "12",
    scope: "Blackjack Round",
    action: "8",
    key: "8",
  },
  {
    id: "13",
    scope: "Blackjack Round",
    action: "9",
    key: "9",
  },
  {
    id: "14",
    scope: "Blackjack Round",
    action: "T",
    key: "0",
  },
  {
    id: "15",
    scope: "Blackjack Round",
    action: "J",
    key: "-",
  },
  {
    id: "16",
    scope: "Blackjack Round",
    action: "Q",
    key: "=",
  },
  {
    id: "17",
    scope: "Blackjack Round",
    action: "K",
    key: "]",
  },
  {
    id: "18",
    scope: "Blackjack Round",
    action: "h",
    key: "q",
  },
  {
    id: "19",
    scope: "Blackjack Round",
    action: "s",
    key: "w",
  },
  {
    id: "20",
    scope: "Blackjack Round",
    action: "d",
    key: "e",
  },
  {
    id: "21",
    scope: "Blackjack Round",
    action: "c",
    key: "r",
  },
];
