import { Keybinding } from "@/types/Keybindings";

export const DefaultKeybinds: Keybinding[] = [
  {
    id: "1",
    scope: "Blackjack PreRound",
    action: "Start Game",
    key: "enter",
    selector: "None",
  },
  {
    id: "2",
    scope: "Blackjack Round",
    action: "Remove Last Card",
    key: "backspace",
    selector: "None",
  },
  {
    id: "3",
    scope: "Blackjack Round",
    action: "Next Turn",
    key: "enter",
    selector: "None",
  },
  {
    id: "24",
    scope: "Blackjack Round",
    action: "Hit",
    key: "space",
    selector: "None",
  },
  {
    id: "22",
    scope: "Blackjack Round",
    action: "Double",
    key: "x",
    selector: "None",
  },
  {
    id: "23",
    scope: "Blackjack Round",
    action: "Split",
    key: "s",
    selector: "None",
  },
  {
    id: "5",
    scope: "Blackjack Round",
    action: "A",
    key: "1",
    selector: "None",
  },
  {
    id: "6",
    scope: "Blackjack Round",
    action: "2",
    key: "2",
    selector: "None",
  },
  {
    id: "7",
    scope: "Blackjack Round",
    action: "3",
    key: "3",
    selector: "None",
  },
  {
    id: "8",
    scope: "Blackjack Round",
    action: "4",
    key: "4",
    selector: "None",
  },
  {
    id: "9",
    scope: "Blackjack Round",
    action: "5",
    key: "5",
    selector: "None",
  },
  {
    id: "10",
    scope: "Blackjack Round",
    action: "6",
    key: "6",
    selector: "None",
  },
  {
    id: "11",
    scope: "Blackjack Round",
    action: "7",
    key: "7",
    selector: "None",
  },
  {
    id: "12",
    scope: "Blackjack Round",
    action: "8",
    key: "8",
    selector: "None",
  },
  {
    id: "13",
    scope: "Blackjack Round",
    action: "9",
    key: "9",
    selector: "None",
  },
  {
    id: "14",
    scope: "Blackjack Round",
    action: "T",
    key: "0",
    selector: "None",
  },
  {
    id: "15",
    scope: "Blackjack Round",
    action: "J",
    key: "minus",
    selector: "None",
  },
  {
    id: "16",
    scope: "Blackjack Round",
    action: "Q",
    key: "=",
    selector: "None",
  },
  {
    id: "17",
    scope: "Blackjack Round",
    action: "K",
    key: "]",
    selector: "None",
  },
  {
    id: "18",
    scope: "Blackjack Round",
    action: "h",
    key: "q",
    selector: "None",
  },
  {
    id: "19",
    scope: "Blackjack Round",
    action: "s",
    key: "w",
    selector: "None",
  },
  {
    id: "20",
    scope: "Blackjack Round",
    action: "d",
    key: "e",
    selector: "None",
  },
  {
    id: "21",
    scope: "Blackjack Round",
    action: "c",
    key: "r",
    selector: "None",
  },
  {
    id: "50",
    scope: "Poker PreRound",
    action: "Start Game",
    key: "enter",
    selector: "None",
  },
  {
    id: "51",
    scope: "Poker Round",
    action: "Check / Call",
    key: "enter",
    selector: "None",
  },
  {
    id: "52",
    scope: "Poker Round",
    action: "Bet / Raise",
    key: "b",
    selector: "None",
  },
  {
    id: "53",
    scope: "Poker Round",
    action: "Fold",
    key: "f",
    selector: "None",
  },
  {
    id: "54",
    scope: "Poker Round",
    action: "Remove Last Card",
    key: "backspace",
    selector: "None",
  },
  {
    id: "55",
    scope: "Poker Round",
    action: "Cancel Bet",
    key: "escape",
    selector: "None",
  },
  {
    id: "56",
    scope: "Poker Round",
    action: "All In",
    key: "a",
    selector: "None",
  },
  {
    id: "65",
    scope: "Poker Round",
    action: "A",
    key: "1",
    selector: "None",
  },
  {
    id: "66",
    scope: "Poker Round",
    action: "2",
    key: "2",
    selector: "None",
  },
  {
    id: "67",
    scope: "Poker Round",
    action: "3",
    key: "3",
    selector: "None",
  },
  {
    id: "68",
    scope: "Poker Round",
    action: "4",
    key: "4",
    selector: "None",
  },
  {
    id: "69",
    scope: "Poker Round",
    action: "5",
    key: "5",
    selector: "None",
  },
  {
    id: "70",
    scope: "Poker Round",
    action: "6",
    key: "6",
    selector: "None",
  },
  {
    id: "71",
    scope: "Poker Round",
    action: "7",
    key: "7",
    selector: "None",
  },
  {
    id: "72",
    scope: "Poker Round",
    action: "8",
    key: "8",
    selector: "None",
  },
  {
    id: "73",
    scope: "Poker Round",
    action: "9",
    key: "9",
    selector: "None",
  },
  {
    id: "74",
    scope: "Poker Round",
    action: "T",
    key: "0",
    selector: "None",
  },
  {
    id: "75",
    scope: "Poker Round",
    action: "J",
    key: "minus",
    selector: "None",
  },
  {
    id: "99",
    scope: "Poker Round",
    action: "Draw Random Card",
    key: "d",
    selector: "None",
  },
  {
    id: "76",
    scope: "Poker Round",
    action: "Q",
    key: "=",
    selector: "None",
  },
  {
    id: "77",
    scope: "Poker Round",
    action: "K",
    key: "]",
    selector: "None",
  },
  {
    id: "78",
    scope: "Poker Round",
    action: "h",
    key: "q",
    selector: "None",
  },
  {
    id: "79",
    scope: "Poker Round",
    action: "s",
    key: "w",
    selector: "None",
  },
  {
    id: "80",
    scope: "Poker Round",
    action: "d",
    key: "e",
    selector: "None",
  },
  {
    id: "81",
    scope: "Poker Round",
    action: "c",
    key: "r",
    selector: "None",
  },
];
